
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/developermichael/ZJPrivateSpecs.git'

platform:ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  pod 'ZJModuleService', :git => 'https://gitee.com/developermichael/ZJModuleService.git'
  pod 'WPKit', :git => 'https://gitee.com/developermichael/WPKit.git'


  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
