
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/WPSpecs.git'

platform:ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  pod 'ZJModuleService', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/ZJModuleService.git'
  pod 'ZJNetwork', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/ZJNetwork.git'
  pod 'WPKit', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/WPKit.git'
  pod 'ZJAppConfig', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/ZJAppConfig.git'
  pod 'WPLogin', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/WPLogin.git'
  pod 'ZJFoundation', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/ZJFoundation.git'
  pod 'WPGlobal', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/WPGlobal.git'
  pod 'WPRequestManager', :git => 'http://47.111.155.56:8800/smcaiot/IOS/WuPan/WPRequestManager.git'
  

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
